### ISSUE TITLE
Problem with attributes

### ISSUE THREAD

**Issue by Cheban1996** [Artem-Romanenia/o2o#4]
Before update to 0.4.0 - all worked good
Today updated version and fetch the error - `"Member instruction 'serde' is not supported."`

Diagnostic message
```
error: Member instruction 'serde' is not supported.
  --> .../mod.rs:14:7
   |
14 |     #[serde(default)]
   |       ^^^^^

```

This error reproduce and for other attributes

Code for reproduce
```
#[derive(Debug, Deserialize, o2o)]
#[owned_into(MyStructDTO)]
struct MyStruct {
    #[serde(default)]
    pub id: i32,
}

struct MyStructDTO {
    pub id: i32,
}
```

**Comment by Artem-Romanenia** [comment]
Thank you for reporting this issue! Please get version 0.4.1, it should be fixed there.

**Comment by Cheban1996** [comment]
Maybe need mark 0.4.0 as deprecated?

**Comment by Artem-Romanenia** [comment]
If I understand correctly, in rust eco-system that would mean yanking the version?

I was looking at `cargo yank` documentation and it says

*Crates should only be yanked in exceptional circumstances, for example, an accidental publish, an unintentional SemVer breakages, or a significantly broken and unusable crate.*

The version is definitely *somewhat* broken, but I can't decide if it is worth yanking since it is somewhat usable still.

Docs also say

*A common workflow is to yank a crate having already published a semver compatible version, to reduce the probability of preventing dependent crates from compiling.*
 
I guess since I have a semver compatible version now, it makes yanking an acceptable move in this case.

Do you know of any alternative to yanking in rust eco-system? Also, if you have any other considerations, please let me know.
