### ISSUE TITLE
Feature Request: Support for TryFrom and TryInto

### ISSUE THREAD

**Issue by PookieBuns** [Artem-Romanenia/o2o#7]
Hi! Thanks to your crate, I have saved hours of work writing boilerplate code! Would it be possible to add attribute macros for implementing TryFrom and TryInto?

**Comment by Artem-Romanenia** [comment]
Hi! Thanks for good words! I've been considering TryFrom and TryInto since forever, but there's one problem: currently my experience with Rust is limited to writing this crate, and there isn't much (or any) need to work with these traits, so I only have superficial idea of how they are typically implemented.

Now that you've shown interest in this, I will try to search for some examples on github and see what would it take to add support for TryFrom and TryInto, but this can take some time.

In a meantime, if you can provide me a couple of examples (as different as possible) of how you would use these, and what code you would expect to get generated, that would be a good start.

**Comment by PookieBuns** [comment]
From a users perspective, I would want to be able to do something like this
```rs
use o2o::o2o;
use std::num::TryFromIntError;

struct MyStructA {
    a: i64,
    b: i64,
}

#[derive(o2o)]
#[try_map_owned(MyStructA, TryFromIntError)]
struct MyStructB {
    #[map(~.try_into())]
    a: i8,
    #[map(~.try_into())]
    b: i8,
}
```
which would expand to
```rs
impl TryFrom<MyStructA> for MyStructB {
    type Error = TryFromIntError;

    fn try_from(value: MyStructA) -> Result<Self, Self::Error> {
        Ok(Self {
            a: value.a.try_into()?,
            b: value.b.try_into()?,
        })
    }
}

impl TryFrom<MyStructB> for MyStructA {
    type Error = TryFromIntError;

    fn try_from(value: MyStructB) -> Result<Self, Self::Error> {
        Ok(Self {
            a: value.a.into(),
            b: value.b.into(),
        })
    }
}
```
Likewise, if it's only a one directional tryfrom, something like this
```rs
#[derive(o2o)]
#[owned_into(MyStructA)]
#[try_from_owned(MyStructA, TryFromIntError)]
struct MyStructC {
    #[into(~.into())]
    #[from(~.try_into())]
    a: i8,
    #[into(~.into())]
    #[from(~.try_into())]
    b: i8,
}
```
will expand to
```rs
impl TryFrom<MyStructA> for MyStructC {
    type Error = TryFromIntError;

    fn try_from(value: MyStructA) -> Result<Self, Self::Error> {
        Ok(Self {
            a: value.a.try_into()?,
            b: value.b.try_into()?,
        })
    }
}
```
I omitted the into since its already a functional feature. 

In terms of resources, i think this [crate](https://crates.io/crates/structural-convert) has implemented this functionality, but obviously if I can have it all in one crate it would be ideal.

Please let me know how else I could help out!

**Comment by Artem-Romanenia** [comment]
Thanks a lot for feedback! I guess I'll have to get into it now) I'll post an update here when I'm done.
