### ISSUE TITLE
Question: How to map different structured enums?

### ISSUE THREAD

**Issue by PookieBuns** [Artem-Romanenia/o2o#8]
Right now, this works
```rs
use o2o::o2o;

#[derive(o2o)]
#[map_owned(MyEnum)]
enum MyEnumUnit {
    #[literal(MyEnum::A(A))]
    A,
}

enum MyEnum {
    A(A),
}

struct A;
```
but this doesn't
```rs
use o2o::o2o;

enum MyEnumUnit {
    A,
}

#[derive(o2o)]
#[map_owned(MyEnumUnit)]
enum MyEnum {
    #[literal(MyEnumUnit::A)]
    A(A),
}

struct A;
```
I have a superficial understanding as to why since it doesn't know how to serialize from MyEnumUnit to MyEnum with the contained struct. Is there a way to use this in the current version of the crate? If not, something like 
```rs
use o2o::o2o;

enum MyEnumUnit {
    A,
}

#[derive(o2o)]
#[map_owned(MyEnumUnit)]
enum MyEnum {
    #[from({MyEnum::A(A)})]
    #[into({MyEnumUnit::A})]
    A(A),
}

struct A;
```
would be something I would be looking for, which provides information for how to serialize from and to

**Comment by Artem-Romanenia** [comment]
So, here you've invented a way of using this crate that I haven't even foreseen) I mostly assumed `#[literal]` to be used with "typical" literals like `123` or `"test"`, so that it can be used to help map enums to primitive types.

`MyEnumUnit::A` or `MyEnum::A(A)` isn't exactly that.. But it can be assigned to a const.. So I guess it qualifies as literal? maybe almost)

To make the second example work, you need to do this:

``` rust
use o2o::o2o;

enum MyEnumUnit {
    A,
}

#[derive(o2o)]
#[map_owned(MyEnumUnit)]
enum MyEnum {
    #[literal(MyEnumUnit::A)]
    A(#[from({A})] /* <-- note this */ A),
}

struct A;
```

It will generate this code:

``` rust
impl std::convert::From<MyEnumUnit> for MyEnum {
    fn from(value: MyEnumUnit) -> MyEnum {
        match value {
            MyEnumUnit::A => MyEnum::A(A /* <-- this is where The A from #[from({A})] goes */),
        }
    }
}
impl std::convert::Into<MyEnumUnit> for MyEnum {
    fn into(self) -> MyEnumUnit {
        match self {
            MyEnum::A(f0) => MyEnumUnit::A,
        }
    }
}
```

But this is already pushing limits of sanity) I need to come up with a better way to map enums for these sorts of cases. Maybe you've noticed there are Type Hints explained in readme, that help map between structs and tuple structs and tuples.. I think I need to figure out a way to make type hints work with enum variants too..

However, I'll keep this issue open until I figure out a better way to do those things..

**Comment by Artem-Romanenia** [comment]
Hi, so, as of version v0.4.6, it can be done differently now.

For your first example:

``` rust
use o2o::o2o;

#[derive(o2o)]
#[map_owned(MyEnum)]
enum MyEnumUnit {
    #[type_hint(as ())]
    #[ghosts(0: {A})]
    A,
}

enum MyEnum {
    A(A),
}

struct A;
```

For the second example:

``` rust
use o2o::o2o;

enum MyEnumUnit {
    A,
}

#[derive(o2o)]
#[map_owned(MyEnumUnit)]
enum MyEnum {
    #[type_hint(as Unit)]
    A(#[ghost({A})]A),
}

struct A;
```

Although it is more ''idiomatic' now, it is hardly more comprehensible, and even somewhat wordier than what you came up with)

This feature is more targeted at cases like this:

``` rust
#[derive(o2o::o2o)]
#[map_owned(EnumDto)]
enum Enum {
    Var1,
    #[type_hint(as ())]
    Var2 {
        field: i32,
        str_field: String
    },
    #[type_hint(as {})]
    Var3(
        #[map(field)] i32,
        #[map(str_field)] String
    )
}

enum EnumDto {
    Var1,
    Var2(i32, String),
    Var3 {field: i32, str_field: String}
}
```

I guess this is all I can think of doing right now. If you have more questions or ideas, please let me know!
